### ISSUE TITLE
JSON property "caption" must not be NULL

### ISSUE THREAD

**Issue by superkresek** [liamcottle/Instagram-SDK-PHP#1]
hey when i run example.loginAndGetTimelineFeed.php i get message JSON property "caption" must not be NULL. i only change the username and password in that script.

my php version is 5.6.21-5+donate.sury.org~trusty+1 

how to get it works? 
thank you

**Comment by liamcottle** [comment]
Hiya,

I have pushed a fix for this in the latest commit. Can you test with `dev-master` rather than the latest stable release.

```
composer require liamcottle/instagram-sdk-php dev-master
```

Cheers.

**Comment by superkresek** [comment]
hey it works.
thank you very very very much.
