### ISSUE TITLE
issue about advert records from get Timeline data

### ISSUE THREAD

**Issue by thinhpc** [liamcottle/Instagram-SDK-PHP#13]
Hi @liamcottle ,

When I call function getTimelineFeed(), I receive a advert media record in my data. It's from Instagram, not from my following or favourite. So I want remove that record.

How do I know what record is advert? Your code can't do it now.

I see that the advert record will have this fields in response data:
ad_action=webclick
ad_header_style=0
ad_link_type=0
dr_ad_type=1

So I think you may want to add a function to determine the advert account for example: isAdvert();
from Instagram\API\Response\Model\FeedItem Class.

Thanks!

**Comment by liamcottle** [comment]
Could you proxy the request and post the JSON as a gist. I don't receive ads in my responses, probably due to where I'm based location wise, so can't check this from my side.

**Comment by thinhpc** [comment]
Please see the request and response from attach files.
you can search for "dr_ad_type" field from response text. That's what I mean above

[request.txt](https://github.com/liamcottle/Instagram-SDK-PHP/files/375335/request.txt)
[response.txt](https://github.com/liamcottle/Instagram-SDK-PHP/files/375336/response.txt)
