### ISSUE TITLE
Class 'CURLFile' not found

### ISSUE THREAD

**Issue by thinhpc** [liamcottle/Instagram-SDK-PHP#26]
I got this error:
Fatal error:  Class 'CURLFile' not found in /var/www/ezgram/vendor/liamcottle/instagram-sdk-php/src/API/Framework/Request.php on line 132

The class CURLFile appear from (PHP 5 >= 5.5.0, PHP 7)
My server is PHP 5.4 so this error occur.

But your composer.json detail is:
required: "php": ">=5.3.0",

I wonder how php 5.3.0 can use this class but php 5.4 can not?

(I tried and confirm it worked on php 5.6)

**Comment by liamcottle** [comment]
Whoops, I'll get the required PHP version updated in `composer.json` when I get a spare moment !

**Comment by liamcottle** [comment]
Fixed by c3eead38e7f9a86597b5a58c676bbe3275d657bb
