### ISSUE TITLE
How to deal with proxy

### ISSUE THREAD

**Issue by GitDov** [liamcottle/Instagram-SDK-PHP#4]
@liamcottle 

Do you have any suggestion of proxy server to use in a production enviroment?
I'm developing a comment tracking system but i dont know what to do next.
And do i need on proxy address/port for each user?
I'm kind of lost on that.

**Comment by liamcottle** [comment]
Hi @GitDov,

Unfortunately I don't have any recommendations on which proxy service provider to use.

I provide all the methods to interact with Instagram, your tracking system implementation is for you to decide on 😄

Cheers.
