### ISSUE TITLE
Get user followers error 

### ISSUE THREAD

**Issue by Farzadpro** [liamcottle/Instagram-SDK-PHP#52]
Hi

I'm trying to get a user followers with this code : 

` $instagram->login("username", "password");`

`$user = $instagram->getUserFollowers("target", "3");`

But i get this error on the output : 

`Instagram Request Failed! [/v1/friendships/target/followers/] [404]`

What is wrong  ?

**Comment by liamcottle** [comment]
You need to pass in the Instagram User's Id or a `User` object. Usernames currently aren't supported.

**Comment by Farzadpro** [comment]
Thanks, you mean like this? 

`$user = $instagram->getUserByUsername("target");`
`$user = $instagram->getUserFollowers($user, "3");`

Tried it didn't work

**Comment by liamcottle** [comment]
You're passing in `3` as the `maxId` value. This will be your problem. Replace it with `null`, and then check if the returned object provides a non-null `next_max_id`. Passing that in as the `maxId` to `getUserFollowers` will let you fetch the next page.
