### ISSUE TITLE
Requests is blocked after 30 min

### ISSUE THREAD

**Issue by haberlook** [liamcottle/Instagram-SDK-PHP#8]
When using timelineFeed.php, if you have requests longer 30 mins, or 300+ refresh request, Instagram will block your IP adress and you will give "Sorry, there was a problem with your request." mesage.

Any idea for sort out?

**Comment by liamcottle** [comment]
I'm not too sure what you mean by "requests longer than 30 mins", but yes, refreshing 300 times in a short amount of time will clearly show to Instagram that you're running a bot of some kind.

Regarding what you said about keeping login cookies, if you take a look at this section of the readme, you'll be able to avoid making many login requests:

https://github.com/liamcottle/Instagram-SDK-PHP#session-management

If for some reason you need to make massive amounts of requests to Instagram, you'd probably want to look at using proxy servers.

**Comment by haberlook** [comment]
I missed this. Just tried like readme file and working fine. Thank you for reply and great script.
